# Generated by Django 4.1 on 2022-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.FileField(default='none', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('IOT', 'IOT'), ('FIRMWARE', 'FIRMWARE'), ('WEBAPPS', 'WEBAPPS')], default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='comments',
            name='txt',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
