# Generated by Django 4.1 on 2022-09-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
